<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CarnamesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ( $this->cars() as $car ) {
            DB::table('car_names')->insert([
                'name' => $car['name'],
                'title' => $car['title'],
                'image' => $car['image'],
            ]);
        }
    }

    public function cars() {
        return $cars = [
            ['image' => 'alfaromeo.png',  'name' => 'Alfa Romeo', 'title' => 'alfaromeo'],
            ['image' => 'astonmartin.png',  'name' => 'Aston Martin', 'title' => 'astonmartin'],
            ['image' => 'atv.png',  'name' => 'Atv', 'title' => 'atv'],
            ['image' => 'audi.png',  'name' => 'Audi', 'title' => 'audi'],
            ['image' => 'baic.png',  'name' => 'Baic', 'title' => 'baic'],
            ['image' => 'bajaj.png',  'name' => 'Bajaj', 'title' => 'bajaj'],
            ['image' => 'bentley.png',  'name' => 'Bentley', 'title' => 'bentley'],
            ['image' => 'bmc.png',  'name' => 'BMC', 'title' => 'bmc'],
            ['image' => 'bmw.png',  'name' => 'BMW', 'title' => 'bmw'],
            ['image' => 'bmwalpina.jpg',  'name' => 'Bmw Alpina', 'title' => 'bmwalpina'],
            ['image' => 'brilliance.png',  'name' => 'Brilliance', 'title' => 'brilliance'],
            ['image' => 'buick.png',  'name' => 'Buick', 'title' => 'buick'],
            ['image' => 'byd.png',  'name' => 'Byd', 'title' => 'byd'],
            ['image' => 'cadillac.png',  'name' => 'Cadillac', 'title' => 'cadillac'],
            ['image' => 'changan.png',  'name' => 'Changan', 'title' => 'changan'],
            ['image' => 'chery.png',  'name' => 'Chery', 'title' => 'chery'],
            ['image' => 'chevrolet.png',  'name' => 'Chevrolet', 'title' => 'chevrolet'],
            ['image' => 'chrysler.png',  'name' => 'Chrysler', 'title' => 'chrysler'],
            ['image' => 'citroen.png',  'name' => 'Citroen', 'title' => 'citroen'],
            ['image' => 'dacia.png',  'name' => 'Dacia', 'title' => 'dacia'],
            ['image' => 'daewoo.png',  'name' => 'Daewoo', 'title' => 'daewoo'],
            ['image' => 'daf.png',  'name' => 'Daf', 'title' => 'daf'],
            ['image' => 'daihatsu.png',  'name' => 'Daihatsu', 'title' => 'daihatsu'],
            ['image' => 'dayun.jpg',  'name' => 'Dayun', 'title' => 'dayun'],
            ['image' => 'dnepr.png',  'name' => 'Dnepr', 'title' => 'dnepr'],
            ['image' => 'dodge.png',  'name' => 'Dodge', 'title' => 'dodge'],
            ['image' => 'dongfeng.png',  'name' => 'DongFeng', 'title' => 'dongfeng'],
            ['image' => 'ducati.png',  'name' => 'Ducati', 'title' => 'ducati'],
            ['image' => 'faw.png',  'name' => 'Faw', 'title' => 'faw'],
            ['image' => 'ferrary.png',  'name' => 'Ferrary', 'title' => 'ferrary'],
            ['image' => 'fiat.png',  'name' => 'Fiat', 'title' => 'fiat'],
            ['image' => 'ford.png',  'name' => 'Ford', 'title' => 'ford'],
            ['image' => 'foton.png',  'name' => 'Foton', 'title' => 'foton'],
            ['image' => 'gac.jpg',  'name' => 'Gac', 'title' => 'gac'],
            ['image' => 'gaz.jpeg',  'name' => 'Gaz', 'title' => 'gaz'],
            ['image' => 'geely.png',  'name' => 'Geely', 'title' => 'geely'],
            ['image' => 'gmc.jpg',  'name' => 'Gmc', 'title' => 'gmc'],
            ['image' => 'greatwall.jpg',  'name' => 'Great Wall', 'title' => 'greatwall'],
            ['image' => 'haojue.png',  'name' => 'Haojue', 'title' => 'haojue'],
            ['image' => 'harleydavidson.png',  'name' => 'Harley Davidson', 'title' => 'harleydavidson'],
            ['image' => 'haval.png',  'name' => 'Haval', 'title' => 'haval'],
            ['image' => 'honda.png', 'name' => 'Honda', 'title' => 'honda'],
            ['image' => 'howo.png', 'name' => 'Howo', 'title' => 'howo'],
            ['image' => 'hummer.jpg', 'name' => 'Hummer', 'title' => 'hummer'],
            ['image' => 'hyundai.png', 'name' => 'Hyundai', 'title' => 'hyundai'],
            ['image' => 'ij.jpg', 'name' => 'IJ', 'title' => 'ij'],
            ['image' => 'infiniti.png', 'name' => 'Infiniti', 'title' => 'infiniti'],
            ['image' => 'irankhodro.png', 'name' => 'Iran Khodro', 'title' => 'irankhodro'],
            ['image' => 'isuzu.jpg', 'name' => 'Isuzu', 'title' => 'isuzu'],
            ['image' => 'iveco.png', 'name' => 'Iveco', 'title' => 'iveco'],
            ['image' => 'jac.png', 'name' => 'JAC', 'title' => 'jac'],
            ['image' => 'jaguar.png', 'name' => 'Jaguar', 'title' => 'jaguar'],
            ['image' => 'jep.jpg', 'name' => 'Jep', 'title' => 'jep'],
            ['image' => 'jonway.jpg', 'name' => 'Jonway', 'title' => 'jonway'],
            ['image' => 'kamaz.jpg', 'name' => 'KamAz', 'title' => 'kamaz'],
            ['image' => 'kavz.png', 'name' => 'KAvZ', 'title' => 'kavz'],
            ['image' => 'kawaski.png', 'name' => 'Kawaski', 'title' => 'kawaski'],
            ['image' => 'khazar.png', 'name' => 'Khazar', 'title' => 'khazar'],
            ['image' => 'kia.png', 'name' => 'Kia', 'title' => 'kia'],
            ['image' => 'kinroad.png', 'name' => 'Kinroad', 'title' => 'kinroad'],
            ['image' => 'kraz.png', 'name' => 'KrAz', 'title' => 'kraz'],
            ['image' => 'ktm.png', 'name' => 'KTM', 'title' => 'ktm'],
            ['image' => 'kuba.jpg', 'name' => 'Kuba', 'title' => 'kuba'],
            ['image' => 'vaz.png', 'name' => 'Lada (VAZ)', 'title' => 'vaz'],
            ['image' => 'lamborghini.png', 'name' => 'Lamborghini', 'title' => 'lamborghini'],
            ['image' => 'landrover.png', 'name' => 'Land Rover', 'title' => 'landrover'],
            ['image' => 'lexus.png', 'name' => 'Lexus', 'title' => 'lexus'],
            ['image' => 'lifan.png', 'name' => 'Lifan', 'title' => 'lifan'],
            ['image' => 'lincoln.png', 'name' => 'Lincoln', 'title' => 'lincoln'],
            ['image' => 'luaz.jpg', 'name' => 'LuAz', 'title' => 'luaz'],
            ['image' => 'man.png', 'name' => 'Man', 'title' => 'man'],
            ['image' => 'maserati.png', 'name' => 'Maserati', 'title' => 'maserati'],
            ['image' => 'maz.png', 'name' => 'Maz', 'title' => 'maz'],
            ['image' => 'mazda.png', 'name' => 'Mazda', 'title' => 'mazda'],
            ['image' => 'mclaren.jpg', 'name' => 'McLaren', 'title' => 'mclaren'],
            ['image' => 'megelli.png', 'name' => 'Megelli', 'title' => 'megelli'],
            ['image' => 'mercedes.png', 'name' => 'Mercedes', 'title' => 'mercedes'],
            ['image' => 'maybach.png', 'name' => 'Mercedes-Maybach', 'title' => 'maybach'],
            ['image' => 'mg.png', 'name' => 'MG', 'title' => 'mg'],
            ['image' => 'mini.png', 'name' => 'Mini', 'title' => 'mini'],
            ['image' => 'minsk.png', 'name' => 'Minsk', 'title' => 'minsk'],
            ['image' => 'mitsubishi.png', 'name' => 'Mitsubishi', 'title' => 'mitsubishi'],
            ['image' => 'mondial.png', 'name' => 'Mondial', 'title' => 'mondial'],
            ['image' => 'moskvich.png', 'name' => 'moskvich', 'title' => 'moskvich'],
            ['image' => 'muravey.jpg', 'name' => 'Muravey', 'title' => 'muravey'],
            ['image' => 'nama.jpg', 'name' => 'Nama', 'title' => 'nama'],
            ['image' => 'neoplan.jpg', 'name' => 'Neoplan', 'title' => 'neoplan'],
            ['image' => 'neptun.jpg', 'name' => 'Neptun', 'title' => 'neptun'],
            ['image' => 'nissan.png', 'name' => 'Nissan', 'title' => 'nissan'],
            ['image' => 'opel.png', 'name' => 'Opel', 'title' => 'opel'],
            ['image' => 'otokar.png', 'name' => 'Otokar', 'title' => 'otokar'],
            ['image' => 'paz.png', 'name' => 'Paz', 'title' => 'paz'],
            ['image' => 'peugeot.png', 'name' => 'Peugeot', 'title' => 'peugeot'],
            ['image' => 'piaggio.jpg', 'name' => 'Piaggio', 'title' => 'piaggio'],
            ['image' => 'renault.png', 'name' => 'Pontiac', 'title' => 'renault'],
            ['image' => 'renault.png', 'name' => 'Porsche', 'title' => 'renault'],
            ['image' => 'renault.jpg', 'name' => 'Ravon', 'title' => 'renault'],
            ['image' => 'renault.png', 'name' => 'Renault', 'title' => 'renault'],
            ['image' => 'rollsroyce.png','name' => 'Rolls-Royce', 'title' => 'rollsroyce'],
            ['image' => 'rover.png','name' => 'Rover', 'title' => 'rover'],
            ['image' => 'saab.jpg', 'name' => 'Saab', 'title' => 'saab'],
            ['image' => 'saipa.jpg', 'name' => 'Saipa', 'title' => 'saipa'],
            ['image' => 'scania.jpg', 'name' => 'Scania', 'title' => 'scania'],
            ['image' => 'seat.png', 'name' => 'SEAT', 'title' => 'seat'],
            ['image' => 'shacman.png', 'name' => 'Shacman', 'title' => 'shacman'],
            ['image' => 'shaolin.png', 'name' => 'Shaolin', 'title' => 'shaolin'],
            ['image' => 'skoda.png', 'name' => 'Skoda', 'title' => 'skoda'],
            ['image' => 'smart.jpg', 'name' => 'Smart', 'title' => 'smart'],
            ['image' => 'ssangyong.png', 'name' => 'Ssang Yong', 'title' => 'ssangyong'],
            ['image' => 'subaru.png', 'name' => 'Subaru', 'title' => 'subaru'],
            ['image' => 'suzuki.png', 'name' => 'suzuki', 'title' => 'suzuki'],
            ['image' => 'tata.jpg', 'name' => 'Tata', 'title' => 'tata'],
            ['image' => 'tesla.png', 'name' => 'Tesla', 'title' => 'tesla'],
            ['image' => 'tofas.png', 'name' => 'Tofas', 'title' => 'tofas'],
            ['image' => 'toyota.png','name' => 'Toyota', 'title' => 'toyota'],
            ['image' => 'uaz.jpg', 'name' => 'UAZ', 'title' => 'uaz'],
            ['image' => 'ural.jpg', 'name' => 'Ural', 'title' => 'ural'],
            ['image' => 'vespa.png', 'name' => 'Vespa', 'title' => 'vespa'],
            ['image' => 'volkswagen.png','name' => 'Volkswagen', 'title' => 'volkswagen'],
            ['image' => 'volvo.png', 'name' => 'Volvo', 'title' => 'volvo'],
            ['image' => 'vosxod.png', 'name' => 'Vosxod', 'title' => 'vosxod'],
            ['image' => 'yamaha.jpg', 'name' => 'Yamaha', 'title' => 'yamaha'],
            ['image' => 'zaz.jpg', 'name' => 'ZAZ', 'title' => 'zaz'],
            ['image' => 'zil.png', 'name' => 'ZIL', 'title' => 'zil'],
            ['image' => 'zongshen.png', 'name' => 'Zongshen', 'title' => 'zongshen'],
            [ 'image' => 'zontes.jpg','name' => 'Zontes', 'title' => 'zontes'],
        ];
    }
}
